steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - gcloud
      - run
      - deploy
      - sena-missions-api
      - --source=api
      - --region=us-central1
      - --platform=managed
      - --allow-unauthenticated
      - --min-instances=1

options:
  logging: CLOUD_LOGGING_ONLY
